# Generated by Django 5.0.3 on 2024-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemMaker',
            new_name='DeviceMaker',
        ),
        migrations.RenameModel(
            old_name='ItemType',
            new_name='DeviceType',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='itemmaker',
            new_name='devicemaker',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='itemtype',
            new_name='devicetype',
        ),
        migrations.AddField(
            model_name='equipment',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
