# Generated by Django 5.0.3 on 2024-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_rename_devicemaker_devicewarranty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicewarranty',
            old_name='maker',
            new_name='warranty',
        ),
    ]
