# Generated by Django 5.0.3 on 2024-04-27 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_equipment_due_date_usagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicewarranty',
            name='warranty',
        ),
        migrations.AddField(
            model_name='devicewarranty',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='devicewarranty',
            name='warranty_period',
            field=models.IntegerField(choices=[(24, '24 months warranty provided'), (12, '12 months warranty provided'), (6, '6 months warranty provided')], default=24),
        ),
    ]
