# Generated by Django 5.0.3 on 2024-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_remove_devicewarranty_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicewarranty',
            name='warranty_period',
            field=models.IntegerField(choices=[(24, '24 months warranty provided'), (12, '12 months warranty provided'), (6, '6 months warranty provided')]),
        ),
    ]
