# Generated by Django 5.0.3 on 2024-04-27 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_alter_devicewarranty_warranty_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicewarranty',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
